matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: ruby
      before_install:
        - export SWIFT_ARCHIVE_URL="https://swift.org/builds/swift-4.0-release/ubuntu1404/swift-4.0-RELEASE/swift-4.0-RELEASE-ubuntu14.04.tar.gz"
        - curl ${SWIFT_ARCHIVE_URL} -o ../swift.tar.gz
        - mkdir ../swift
        - tar xzf ../swift.tar.gz -C ../swift --strip-components 1
        - export PATH="$(pwd)/../swift/usr/bin:${PATH}"
    - os: osx
      osx_image: xcode9
      sudo: required
      language: objective-c

script:
  - swift build
  - swift test
