branches:
  except:
    - /^\d+\.\d+\.\d+(-\S*)?$/

os:
  - linux
  - osx
language: generic
sudo: required
osx_image: xcode10.2
dist: xenial
env:
  - SWIFT_BUILD_OPTION="-Xswiftc -swift-version -Xswiftc 4"
  - SWIFT_BUILD_OPTION="-Xswiftc -swift-version -Xswiftc 4.2"
  - SWIFT_BUILD_OPTION="-Xswiftc -swift-version -Xswiftc 5"
before_install:
  - |
    if [ $(uname) = "Linux" ]; then
      export SWIFT_ARCHIVE_URL="https://swift.org/builds/swift-5.0-release/ubuntu1604/swift-5.0-RELEASE/swift-5.0-RELEASE-ubuntu16.04.tar.gz"
      curl ${SWIFT_ARCHIVE_URL} -o ../swift.tar.gz
      mkdir ../swift
      tar xzf ../swift.tar.gz -C ../swift --strip-components 2
      export PATH="$(dirname $(pwd))/swift/bin:$PATH"
    fi
script:
  - swift build ${SWIFT_BUILD_OPTION}
  - swift build --configuration release ${SWIFT_BUILD_OPTION}
  - swift test ${SWIFT_BUILD_OPTION}
